### ISSUE TITLE
The file was installed in python path, and will result in error in import.

### ISSUE THREAD

**Issue by lrtfm** [connorjward/firedrake-spack#1]
Thanks for creating this repo to install firedrake with spack.

After install the testing version, I get the following errors when import firedrake.
```
zzyang@MathWorkstation: ~
$ python
Python 3.8.10 (default, Jun  4 2021, 19:24:32)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import firedrake
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg/firedrake/__init__.py", line 28, in <module>
    firedrake_configuration.setup_cache_dirs()
  File "/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg/firedrake_configuration/__init__.py", line 43, in setup_cache_dirs
    os.environ["PYOP2_CACHE_DIR"] = os.path.join(config["options"]["cache_dir"], "pyop2")
KeyError: 'cache_dir'
```

Then I copy the file to the python path, and another error shows up.
```
zzyang@MathWorkstation: ~
$ cp /home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/py-firedrake-testing-5wii6ngzbo7qi325hd73h2wypcy56qpv/.configuration.json /home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg/firedrake_configuration/configuration.json
zzyang@MathWorkstation: ~
$ python
Python 3.8.10 (default, Jun  4 2021, 19:24:32)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import firedrake
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg/firedrake/__init__.py", line 39, in <module>
    from pyop2 import op2                        # noqa: F401
  File "/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/py-pyop2-master-qfjxifxctyo4eha6v6cgbbha7dnjr5ww/lib/python3.8/site-packages/pyop2/__init__.py", line 4, in <module>
    from pyop2.op2 import *  # noqa
  File "/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/py-pyop2-master-qfjxifxctyo4eha6v6cgbbha7dnjr5ww/lib/python3.8/site-packages/pyop2/op2.py", line 42, in <module>
    from pyop2.sequential import par_loop, Kernel  # noqa: F401
  File "/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/py-pyop2-master-qfjxifxctyo4eha6v6cgbbha7dnjr5ww/lib/python3.8/site-packages/pyop2/sequential.py", line 42, in <module>
    from pyop2 import base
  File "/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/py-pyop2-master-qfjxifxctyo4eha6v6cgbbha7dnjr5ww/lib/python3.8/site-packages/pyop2/base.py", line 64, in <module>
    import loopy
  File "/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/py-loopy-firedrake-ldx2zmspv6acaeokaegnk276oyzl4gv3/lib/python3.8/site-packages/loopy/__init__.py", line 27, in <module>
    from loopy.translation_unit import for_each_kernel
  File "/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/py-loopy-firedrake-ldx2zmspv6acaeokaegnk276oyzl4gv3/lib/python3.8/site-packages/loopy/translation_unit.py", line 43, in <module>
    from pyrsistent import pmap, PMap
ModuleNotFoundError: No module named 'pyrsistent'
```
I think this one can be fixed by add `depends` in the package file.

The first error maybe caused by installing the files in python path other than firedrake path?
How can I install the file in the proper palce?
```
zzyang@MathWorkstation: ~
$ find /home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8* -name '*firedrake*'
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/bin/firedrake-clean
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/bin/firedrake-install
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/bin/firedrake-preprocess-bibtex
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/bin/firedrake-status
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/bin/firedrake-zenodo
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg/EGG-INFO/scripts/firedrake-clean
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg/EGG-INFO/scripts/firedrake-install
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg/EGG-INFO/scripts/firedrake-preprocess-bibtex
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg/EGG-INFO/scripts/firedrake-status
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg/EGG-INFO/scripts/firedrake-zenodo
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg/firedrake
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg/firedrake_citations
/home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/python-3.8.10-w53qlewfh5ywh4sc4zicthpizfgh32jy/lib/python3.8/site-packages/firedrake-0+untagged.1.gc3b5440-py3.8-linux-x86_64.egg/firedrake_configuration
zzyang@MathWorkstation: ~
$ ls /home/zzyang/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.3.0/py-firedrake-testing-5wii6ngzbo7qi325hd73h2wypcy56qpv/lib/python3.8/site-packages/
zzyang@MathWorkstation: ~
$
```

**Comment by connorjward** [comment]
Hi, I'm really sorry for getting your hopes up but this repository is still very much a work in progress and I haven't managed to get all of the errors fixed yet. I'll make this clear in the README to avoid confusion.

For now the best way to install Firedrake is still with the `firedrake-install` script (see https://firedrakeproject.org/download.html for more details). If you are trying to install to HPC then ask on our Slack channel if you encounter any problems.

**Comment by lrtfm** [comment]
> Hi, I'm really sorry for getting your hopes up but this repository is still very much a work in progress and I haven't managed to get all of the errors fixed yet. I'll make this clear in the README to avoid confusion.
> 
> For now the best way to install Firedrake is still with the `firedrake-install` script (see https://firedrakeproject.org/download.html for more details). If you are trying to install to HPC then ask on our Slack channel if you encounter any problems.

Got it. Thanks for your quick reply.
